### ISSUE TITLE
Create teams api crashing when trying to create teams

### ISSUE THREAD

**Issue by kozaktar** [hatchways/team-yugioh#161]
![image.png](https://images.zenhubusercontent.com/5ff4d36438a8fe581e1d733b/d8c63e79-6fd6-4a20-83cb-580269a03e86)

TypeError: Promise.allSettled is not a function
    at C:\Users\taras-kozak\Desktop\hatchways\calendar app\team-yugioh\server\routes\teamAPI.js:16:33
    at Layer.handle [as handle_request] (C:\Users\taras-kozak\Desktop\hatchways\calendar app\team-yugioh\server\node_modules\express\lib\router\layer.js:95:5) 
    at next (C:\Users\taras-kozak\Desktop\hatchways\calendar app\team-yugioh\server\node_modules\express\lib\router\route.js:137:13)
    at C:\Users\taras-kozak\Desktop\hatchways\calendar app\team-yugioh\server\middleware\auth.js:24:7
    at C:\Users\taras-kozak\Desktop\hatchways\calendar app\team-yugioh\server\node_modules\njwt\index.js:63:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by WhoaNellie** [comment]
Currently it creates a team for me but doesn't close the dialog after it's been created

**Comment by kozaktar** [comment]
fixed in pull request #179
